version: '3.8'
services:
  db:
    image: postgres:14
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: pokedex
    ports:
      -  5432:5432
    # volumes:
    #   - ./data:/var/lib/postgresql/data
  
  api:
    build: .
    container_name: api
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/pokedex
      OAUTH_CLIENT_ID: pokedex
      OAUTH_CLIENT_SECRET: pokedex
      JWT_SECRET: secret
      PORT: 80
    depends_on:
      - db
    ports:
      -  8080:80

# volumes:
#   data: