version: '3.8'
services:
  db:
    image: postgres:14
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      
    # volumes:
    #   - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
  api:
    build: .
    container_name: api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 3001:3001
    depends_on:
      - db

# volumes:
#   data: